# Computer Programming
It is simply to tell computers what to do using simple but precise instructions. A programming language (like Python) is the set of all primitive instuctions avalable to you to tell the computer what to do. A combination of these primitive instructions is called a "computer program".

# Python is Interpreted
Different from other popular programming languages such as C and C++, Python is interpreted. What this means for us is that Python commands can be executed inmmediately after typing them since there is no need of compiling the code before execution.


In [1]:
website = "https://example.com"
print (website)

https://example.com


In [2]:
2+6

8

In [3]:
2-8

-6

In [4]:
x=5
y='One small step for man, '
a='one giant leap for mankind'
z=6.0

In [5]:
x+z

11.0

In [6]:
y+a  #

'One small step for man, one giant leap for mankind'

# Assignments versus equations
In Python when we write <code>x=3</code> is means something different than in the mathematical equation $x=3$

In mathemathics once we define the equation we can assume that x=3 will keep it value for the entire computation or for the entire mathematical model. In programming  <code>x=3</code> just means that 3 is the current value of <code>x</code> but it could be changed at will with the next instruction. We call this "binding" a variable to a value.

In [7]:
x=3
print ("hello")
print ("The value of x is", x)
x="Three"
print ("The value of x is", x)
x=3.14159
print ("The value of x is", x)


hello
The value of x is 3
The value of x is Three
The value of x is 3.14159


# Functions
Functions in Python can be called simply by typing the function name and putting their arguments in parenthesis. Some examples follow, for a complete list of Python Build-in functions see: https://www.w3schools.com/python/python_ref_functions.asp

In [8]:
abs(-5)

5

In [9]:
round(99.99)

100

In [10]:
x=3.14159
type(x)

float

In [ ]:
input()

# Primitive data types

Data Structures are simply how computers store information. Below are listed the most primitive or basic data structures. These structures are the building blocks for data storage and manipulation and they contain pure, simple values of data. Python has four primitive variable types:

- Integers (simple counting numbers)
- Float (number using decimal points)
- Strings (strings of letter or characters)
- Boolean (boolen number can only be '0' or '1', TRUE or FALSE)

## Floats
- Define floats x, y
- Assign numerical values to x, y
- Execute basic aritmetic operation on x,y
- How to prompt the "user" to setup the x and y values?
- How to change the numerical values assigned to x,y?

In [ ]:
x = 4.0
y = 2.0

print ("Using + we obtain:", x + y)
print ("Using * we obtain:", x * y)      # returns multiplication
print ("Using / we obtain:", x / y)
print ("Using % we obtain:", x % y)      # Returns the remainder
print ("Using abs() we obtain:", abs(x))     # Absolute value
print ("Using ** we obtain:", x ** y)     # x to the power y 

## Strings

In [ ]:
# String

x = "Industrial Engineering"
y = "Management Systems"

x + " & " + y


Here are some other basic operations that you can perform with strings; For example, you can use * to repeat a string a certain number of times:

In [ ]:
# repeat

x * 3

You can also "slice" strings, which means that you select parts of strings:

In [ ]:
# Range slicing

stringSegment1 = x[2:]

print(stringSegment1)


# Slicing

stringSegment2 = y[0] + y[1]

print(stringSegment2)

Note that strings can also be alpha-numeric characters, but that the + operation still is used to concatenate strings.

In [ ]:
x = "4"
y = "3"

x + y

Some string operations: calculating string length <code>len()</code>, string in upper caps<code>upper()</code>, string in lower caps <code>lower()</code>

In [ ]:
a = "University of Central Florida"
a_lenght = len(a)
a_uppercased = a.upper()
a_lowercased = a.lower()

print (a_lenght)
print (a_uppercased)
print (a_lowercased)

## Boolean

In [ ]:
# Boolean

x = 4

y = 2

x == y

#x > y

In [ ]:
x = 4
y = 6
z = (x == y)      # Comparison expression 

if z:             # Conditional on truth/false value of "z
    print ("Engineering")
else: print ("Not Engineering")

In [ ]:
z = True         # direct assigment to "true"

if z:             # Conditional on truth/false value of "z
    print ("Engineering")
else: print ("Not Engineering")

## Function Type()
To check the type of an object in Python, use the built-in type() function, just like in the lines of code below:

In [ ]:
a = 4.0
b = "Class"
c = 12

type(a) 

In [ ]:
type(b)

In [ ]:
type(c)

## Non-Primitive data structures

#### The  non-primitive data structures in Python are divided into:
- Lists
- Arrays

### Lists
Easy to use, good for everything except numbers and calculations

In [ ]:
cars = ["Ford", "Volvo", "BMW"]
print(cars)

List can be changed:

In [ ]:
cars.append("Honda")
print(cars)

In [ ]:
gains = [100, 200, 280]
print(gains)
print(gains[0])

In [1]:
gains[0]/3.0

NameError: name 'gains' is not defined

In [ ]:

gains/3.0 #error! entire list can not be divided even if they are lists of number, that why we need....Arrays

This ```error``` shows that a division operator is not defined for lists. We need a different kind of structure for this...

### Arrays
Use arrays for numbers. To use arrays, you need to "import" the numerical package Numpy.

In [3]:
pip install numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 545.5 kB/s eta 0:00:00a 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

gains2 = np.array([100, 200, 280])
print(gains2)
print(gains2/3.0)


[100 200 280]
[33.33333333 66.66666667 93.33333333]


## Referencing variables
- When we assign (bind) a variable to a value in Python we create a __reference__.

- A reference is different from the actual value that it refers to.

- Variables are names for references.

Below we have variables <code>colors</code> and <code>colors2</code> both assigned to the same value <code>['red', 'blue', 'green'] </code>

In [ ]:
colors = ['red', 'blue', 'green']
colors2 = colors
print (colors)
print (colors2)

Now lets change values on variable <code>colors</code> and see what happens to <code>colors2</code>:

In [ ]:
colors.append("yellow")
print (colors)
print (colors2)

# Exercises

__1.__ Calculate the following mathematical expression using Phyton: 
$6x^5+x^2$ , for a value of $x=4$


In [5]:
x=4
y = 6*x**5+x**2
print ("The value of y is",y)


The value of y is 6160


__2.__ Calculate the expression in above exercise but for x=2500

In [6]:
x=2500
y = 6*x**5+x**2
print ("The value of x=2500 is",y)

The value of x=2500 is 585937500006250000


__3.__ Calculate the following mathematical expression using Phyton: 
$\dfrac{6x^5}{y}+x^2+\sqrt{xy}$ , for a value of $x=4$ and $y=46$

In [8]:
import math

x=4
y=46
z = (6*x**5/y)+x**2+math.sqrt(x*y)
print ("The value of x=4 and y = 46 is",z)

The value of x=4 and y = 46 is 163.12987735755488


__4.__ Create a variable string1 with value "Desicion Support Systems". Using string "slicing" extract the word "Support" from string1

In [13]:
string1 = "Decision Support Systems"
stringseg = string1[9:16]
print(stringseg)

Support


__5.__ Create a list with the following values: "one", "two", "three". Then use function "append" to add to this list the element "four".

In [16]:
list = ["one","two","three"]
print(list)
list2 =list.append("four") 
print(list)

['one', 'two', 'three']
['one', 'two', 'three', 'four']


__6.__ Create an "array" wiht values (3,5,8,122). Multiply this array by 5 and display the answer.

In [22]:

import numpy as np
array = np.array([3,5,8,122])
multarray = array*5
print(array)
print(multarray)

[  3   5   8 122]
[ 15  25  40 610]


# Applications

# Homework (not graded)
Please complete all the exercises on this Notebook. Some exercises will be solved in class, but you should complete solving all the remaining exersices at the end of each Notebook on every class. If you can not solve an exercise, please contact the class teaching assistant for help inmmediately.